apiVersion: v1
data:
  MONGODB_APP_NAME: Q2x1c3RlcjA=
  MONGODB_DB_NAME: bXl0b2RvZGI=
  MONGODB_HOST: Y2x1c3RlcjAubXAzbHllYy5tb25nb2RiLm5ldA==
  MONGODB_PASSWORD: UU0zZGJ5Smlxcm9LYXg3aQ==
  MONGODB_USERNAME: a2FudXBhdWw=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"mongo-secret","namespace":"default"},"stringData":{"MONGODB_APP_NAME":"Cluster0","MONGODB_DB_NAME":"mytododb","MONGODB_HOST":"cluster0.mp3lyec.mongodb.net","MONGODB_PASSWORD":"QM3dbyJiqroKax7i","MONGODB_USERNAME":"kanupaul"},"type":"Opaque"}
  creationTimestamp: "2026-08-18T00:27:28Z"
  name: mongo-secret
  namespace: my-school-app
  resourceVersion: "3798"
  uid: 857434e7-df20-40c2-b915-f4213af141db
type: Opaque
